name: Create envfile

on:
  push:
    branches:
      - 'main'
      - 'gh-pages'

jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: zacharybaca/password-generator-api-project@main
      with:
        envkey_DEBUG: false
        envkey_PASSWORD_GENERATOR_API_KEY: ${{ secrets.PASSWORD_GENERATOR_API_KEY }}
        file_name: .env
      
    - name: Build Process
      run: |
          npm run predeploy
          npm run build
          npm run deploy
